### ISSUE TITLE
Fuzzy translations are not considered as exportable

### ISSUE THREAD

**Issue by kayneth** [php-translation/loco-adapter#38]
Hi !

I've seen that "Fuzzy" translations are not exported.
Should we consider it as normal ? Should we make it as configurable through the Symfony Bundle ? 
Depending on environment (development, production, etc.) we would want to keep translations or not if the status changes.

Thank you ! :smile:

**Comment by Tynael** [comment]
I am also interested to find out how can I download translations that are flagged are "Fuzzy", "Provisional" or simply download all translations despite of their flags.
@kayneth, did you find a solution to this?

cc: @Nyholm

**Comment by kayneth** [comment]
Hi :)

For the project I worked on, we didn't bother to change this because our client didn't see it as a problem. 
But i think i decorated the Loco adapter for another need. I or you could do the same for now if this is too specific to be a part of the loco-adapter package. 

And I saw this PR that could respond to your need #43

**Comment by Nyholm** [comment]
Im closing this since the status of the translations are configurable. 

```yaml
# /app/config/config.yml
translation_adapter_loco:
  index_parameter: 'id' 
  projects:
    acme:
      api_key: 'foobar'   
      domains: ['messages', 'navigation']
      status:  '!untranslated,!rejected'
```
